address comments from Jeanne & Diontje

diff --git a/packer/HWIMO-BUILD b/packer/HWIMO-BUILD
--- a/packer/HWIMO-BUILD
+++ b/packer/HWIMO-BUILD
@@ -209,15 +209,16 @@ else
     echo "${INFO_HEADER}No signing to be performed.. skip."
 fi
 
-# Conver the VM Disk and VMX folder into an OVA
-
 BASENAME=${VM_NAME}
 OVA="${BASENAME}.ova"
-ovftool $SIGN_ARGS -o ${VMDIR}/${VM_NAME}.vmx $OVA
 
-if [ $? != 0 ]; then
-    echo "${ERROR_HEADER} ovftool exec failed.. exit"
-    exit 4
+# Conver the VM Disk and VMX folder into an OVA
+if [ "$BUILD_TYPE"  == "vmware" ];  then
+    ovftool $SIGN_ARGS -o ${VMDIR}/${VM_NAME}.vmx $OVA
+    if [ $? != 0 ]; then
+        echo "${ERROR_HEADER} ovftool exec failed.. exit"
+        exit 4
+    fi
 fi
 
 # Do Virus Scan
@@ -233,7 +234,11 @@ fi
 
 if [ "${CUSTOMIZED_PROPERTY_OVA}" == "true" ];
 then
-    add_IP_property_to_ova.sh ${OVA} 
+    bash add_IP_property_to_ova.sh ${OVA}
+    if [ $? != 0 ]; then
+         echo "${ERROR_HEADER} add_IP_property_to_ova.sh ${OVA} failed! Abort!"
+         exit 5
+    fi
 fi # End of [ "${CUSTOMIZED_PROPERTY_OVA}" == "true" ]
 
 
