modify based on PR comments
use ENV for ATLAS_TOKEN instead of parameter
refine the comments

diff --git a/packer/HWIMO-BUILD b/packer/HWIMO-BUILD
--- a/packer/HWIMO-BUILD
+++ b/packer/HWIMO-BUILD
@@ -2,60 +2,67 @@
 
 ###################################################
 # input (enviromental variable):
-# * OS_VER        -   ubuntu-14.04 or ubuntu-16.04
-# * BUILD_TYPE    -   vmware or virtualbox
-# * RACKHD_INSTALL_ANSIBLE - which is the ansible yml playbook used. now are rackhd_ci_builds, rackhd_release or rackhd_local
-# * RACKHD_VERSION        - optional , by default is blank. used for rackhd_ci_builds.yml to install specific version of rackhd.deb, and moreover, this version used to version the vagrant box when uploading to ATLAS
-# * UPLOAD_BOX_TO_ATLAS   - optional, by default is False. tell packer if upload the vagrant box generated to ATLAS. NOTE: ATLAS user/token and target ATLAS repo name should be specificed.
+# * OS_VER        -   ubuntu-14.04 or ubuntu-16.04, by default is ubuntu-14.04
+# * BUILD_TYPE    -   vmware or virtualbox, by default is virtualbox
+# * ANSIBLE_PLAYBOOK - which is the ansible yml playbook used. options are rackhd_package, rackhd_ci_builds, rackhd_release or rackhd_local, default is rackhd_local.
+# * RACKHD_VERSION        - optional , by default is blank(will apt-get install latest rackhwill apt-get install latest rackhd). used for rackhd_ci_builds.yml to install specific version of rackhd.deb(refer to https://bintray.com/rackhd to find correct version you need)
+# * UPLOAD_BOX_TO_ATLAS   - optional, by default is false. tell packer if upload the vagrant box generated to ATLAS. NOTE: ATLAS user/token and target ATLAS repo name should be specificed.
 # * ATLAS_USERNAME - optional, required only when UPLOAD_BOX_TO_ATLAS is true.
 # * ATLAS_NAME     - optional, required only when UPLOAD_BOX_TO_ATLAS is true.
 # * ATLAS_TOKEN    - optional, required only when UPLOAD_BOX_TO_ATLAS is true.
 # * ATLAS_VERSION  - optional, by default is "".when UPLOAD_BOX_TO_ATLAS is true, the box will be uploaded to ATLAS as ATLAS_VERSION( format only accepts like 1.2.3).
 ###################################################
 
-
-
+INFO_HEADER="[Info]"
+WARNING_HEADER="[Warning]"
+ERROR_HEADER="[Error]"
 
 # early exit on command failure
 set -e
 
-echo '[Info] Please use ENV VAR to pass customized parameter to this script. Please refer to the usage on the top of script file.'
+echo ${INFO_HEADER}" Please use ENV VAR to pass customized parameter to this script. Please refer to the usage on the top of script file."
 
 ############################  Parameter Process ################ start #############
 
-#Ubuntu Version
+####  Ubuntu Version  ###
 if  [ ! -n "${OS_VER}" ];  then
     OS_VER=ubuntu-14.04
 fi
-echo "[Info] Packer Build based on $OS_VER"
+echo "${INFO_HEADER} Packer Build based on $OS_VER ( using template-${OS_VER}.json)"
 
-# Build Vagrant or VMware OVA ?
+#### Build Vagrant or VMware OVA ? ###
 if  [ ! -n "${BUILD_TYPE}" ];  then
     BUILD_TYPE=virtualbox  # option is vmware or vitrualbox , case senstive
 fi
+if [[ ${BUILD_TYPE} != "virtualbox" ]] && [[ ${BUILD_TYPE} != "vmware" ]] ; then
+    echo "${ERROR_HEADER} Bad Env Var: the BUILD_TYPE=$BUILD_TYPE is invalid, it should be either virtualbox or vmware.. "
+    exit 2
+fi
 
-echo "[Info] Packer Build : ${BUILD_TYPE}"
+echo "${INFO_HEADER} Packer Build : ${BUILD_TYPE}"
 
-
+#### if upload vagrant box to ATLAS ###
 IS_UPLOAD_ATLAS=false
-if [[ "${UPLOAD_BOX_TO_ATLAS}" == "true" ]] ||  [[ "${UPLOAD_BOX_TO_ATLAS}" == "TRUE" ]];
+if [[ ${UPLOAD_BOX_TO_ATLAS,,} == "true" ]];
 then
     IS_UPLOAD_ATLAS=true
 fi
 if [ $BUILD_TYPE != "virtualbox" ] && [ $IS_UPLOAD_ATLAS == true ]; then
-    echo "[Error]: Bad Env Var: only when for Vagrant Box build. ( BUILD_TYPE=virtualbox), the $UPLOAD_BOX_TO_ATLAS can be set to true . Abort !"
-    exit 1
+    echo "${ERROR_HEADER} Bad Env Var: only when for Vagrant Box build. ( BUILD_TYPE=virtualbox), the $UPLOAD_BOX_TO_ATLAS can be set to true . Abort !"
+    exit 2
 fi
+
+### Check the ATLAS accounts ###
 if [ $IS_UPLOAD_ATLAS == true ]; then
    if [ ! -n "${ATLAS_USERNAME}" ] || [ ! -n "${ATLAS_NAME}" ] || [ ! -n "${ATLAS_TOKEN}" ];  then
-       echo "[Error]: Bad Env Var: When ENV VAR \$UPLOAD_BOX_TO_ATLAS is true, the ATLAS_USERNAME/ATLAS_NAME/ATLAS_TOKEN should be given.  Abort !"
+       echo "${ERROR_HEADER} Bad Env Var: When ENV VAR \$UPLOAD_BOX_TO_ATLAS is true, the ATLAS_USERNAME/ATLAS_NAME/ATLAS_TOKEN should be given.  Abort !"
        exit 2
    fi
    if [ ! -n "${ATLAS_VERSION}" ];  then
        ATLAS_VERSION=""
    else
        if [[ $ATLAS_VERSION != +([0-9]).+([0-9]).+([0-9]) ]] ; then
-           echo "[Error]: ATLAS_VERSION(${ATLAS_VERSION}) should be X.Y.Z (X.Y.Z is digit), that's only format accepted by ATLAS."
+           echo "${ERROR_HEADER}: ATLAS_VERSION(${ATLAS_VERSION}) should be X.Y.Z (X.Y.Z is digit), that's only format accepted by ATLAS."
           exit 2
       fi
    fi
@@ -64,22 +71,26 @@ fi
 
 # By default. use ansible playbook : rackhd_local.yml
 # can become an ENV VAR in the future
-if  [ ! -n "${RACKHD_INSTALL_ANSIBLE}" ];  then
-    RACKHD_INSTALL_ANSIBLE=rackhd_local
+if  [ ! -n "${ANSIBLE_PLAYBOOK}" ];  then
+    ANSIBLE_PLAYBOOK=rackhd_local
 fi
-echo "[Info] Install RackHD with ansible :  ${RACKHD_INSTALL_ANSIBLE}.yml "
+if [ ! -f "ansible/${ANSIBLE_PLAYBOOK}.yml" ]; then
+    echo "${ERROR_HEADER} The target ansible playbook(ansible/${ANSIBLE_PLAYBOOK}.yml) does not exist. Aborting..."
+    exit 3
+fi
+echo "${INFO_HEADER} Install RackHD with ansible :  ${ANSIBLE_PLAYBOOK}.yml "
 
-
+### $RACKHD_VERSION is used for package install provisioner:  `apt-get install rackhd=$RACKHD_VERSION` ###
 
 if [  -n "${RACKHD_VERSION}" ];  then
-   if [ $RACKHD_INSTALL_ANSIBLE != "rackhd_local" ]; then
-       echo "[Info] Build VM based on RackHD Debian Package ${RACKHD_VERSION} "
+   if [ $ANSIBLE_PLAYBOOK != "rackhd_local" ]; then
+       echo "${INFO_HEADER} Build VM based on RackHD Debian Package ${RACKHD_VERSION} "
   else
-       echo "[Warning] Skip the ENV VAR: RACKHD_VERSION=$RACKHD_VERSION, this variable is useless for rackhd_local.yml (build from src code)".
+       echo "${WARNING_HEADER} Skip the ENV VAR: RACKHD_VERSION=$RACKHD_VERSION, this variable is useless for rackhd_local.yml (build from src code)".
    fi
 else
-   if [ $RACKHD_INSTALL_ANSIBLE != "rackhd_local" ]; then
-       echo "[Info] Install RackHD Package without specific version."
+   if [ $ANSIBLE_PLAYBOOK != "rackhd_local" ]; then
+       echo "${INFO_HEADER} Install RackHD Package without specific version."
    fi
 fi
 
@@ -103,15 +114,15 @@ VM_NAME=rackhd-${OS_VER}
 CFG_FILE=template.cfg
 # parameter file pass to packer
 echo {                                                > $CFG_FILE
-echo  \"playbook\": \"${RACKHD_INSTALL_ANSIBLE}\",   >> $CFG_FILE
+echo  \"playbook\": \"${ANSIBLE_PLAYBOOK}\",         >> $CFG_FILE
 echo  \"vm_name\": \"${VM_NAME}\"                    >> $CFG_FILE
 
 if [[ $IS_UPLOAD_ATLAS == true ]]
 then
+    # NOTE: the ATLAS_TOKEN should be hiden in ENV Variable for security sake.
     echo ,                                           >> $CFG_FILE
     echo \"atlas_username\": \"${ATLAS_USERNAME}\" , >> $CFG_FILE
     echo \"atlas_name\": \"${ATLAS_NAME}\" ,         >> $CFG_FILE
-    echo \"atlas_token\": \"${ATLAS_TOKEN}\" ,       >> $CFG_FILE
     echo \"atlas_version\": \"${ATLAS_VERSION}\"     >> $CFG_FILE
 fi
 echo }                                               >> $CFG_FILE
@@ -148,7 +159,7 @@ PACKER_TEMP=$(cat template-${OS_VER}.json)
 if [[ $IS_UPLOAD_ATLAS == false ]]
 then
     if [ ! -n "$(which jq)" ] ; then
-        echo "[Error] jq is not installed . please install it, e.x. sudo apt-get install jq... Aborting. "
+        echo "${ERROR_HEADER} jq is not installed . please install it, e.x. sudo apt-get install jq... Aborting. "
         exit 5
     fi
     # Delete the post-processors blocks in the template.json, before sending to 'packer build'
@@ -161,12 +172,12 @@ fi
 echo ${PACKER_TEMP} | $PACKER build --force --only=${BUILD_TYPE}-iso --var-file=$CFG_FILE  - | $TS | tee packer-install.log 
 
 if [ $? != 0 ]; then
-    echo "[Error] Packer Build failed.. exit"
+    echo "${ERROR_HEADER} Packer Build failed.. exit"
     exit 3
 fi
 
 if [ "$BUILD_TYPE"  != "vmware" ];  then
-    echo "Skip the post-processing(signing/clamscan/ovf-template injection) for virtualbox for the time being ..."
+    echo "${INFO_HEADER} Skip the post-processing(signing/clamscan/ovf-template injection) for virtualbox for the time being ..."
     exit 0
 fi
 
@@ -175,9 +186,9 @@ fi
 if [ -f "$CI_SIGNING_KEY" ]
 then
     SIGN_ARGS="--privateKey=$CI_SIGNING_KEY"
-    echo "[Info]Signing the OVA with the CI key"
+    echo "${INFO_HEADER}Signing the OVA with the CI key"
 else
-    echo "[Info]No signing to be performed.. skip."
+    echo "${INFO_HEADER}No signing to be performed.. skip."
 fi
 
 # Conver the VM Disk and VMX folder into an OVA
@@ -187,18 +198,18 @@ OVA="${BASENAME}.ova"
 ovftool $SIGN_ARGS -o ${VMDIR}/${VM_NAME}.vmx $OVA
 
 if [ $? != 0 ]; then
-    echo "[Error] ovftool exec failed.. exit"
+    echo "${ERROR_HEADER} ovftool exec failed.. exit"
     exit 4
 fi
 
 # Do Virus Scan
 if [ -x /usr/bin/clamscan ]
 then
-    echo "[Info] Doing ClamScan"
+    echo "${INFO_HEADER} Doing ClamScan"
     rm -rf "$OVA.avscan"
     /usr/bin/clamscan --log="$OVA.avscan" --max-filesize=4000M --max-scansize=4000M -r ${VMDIR} --allmatch
 else
-    echo "[Info] skip clamscan..."
+    echo "${INFO_HEADER} skip clamscan..."
 fi
 
 
