Add ATLAS/VERSION into HWIMO-BUILD, and remove duplicated template-packages.json

diff --git a/packer/HWIMO-BUILD b/packer/HWIMO-BUILD
--- a/packer/HWIMO-BUILD
+++ b/packer/HWIMO-BUILD
@@ -4,7 +4,13 @@
 # input (enviromental variable):
 # * OS_VER        -   ubuntu-14.04 or ubuntu-16.04
 # * BUILD_TYPE    -   vmware or virtualbox
-# * RACKHD_INSTALL_ANSIBLE - which is the ansible yml playbook used. now are rackhd_package or rackhd_local
+# * RACKHD_INSTALL_ANSIBLE - which is the ansible yml playbook used. now are rackhd_ci_builds, rackhd_release or rackhd_local
+# * RACKHD_VERSION        - optional , by default is blank. used for rackhd_ci_builds.yml to install specific version of rackhd.deb, and moreover, this version used to version the vagrant box when uploading to ATLAS
+# * UPLOAD_BOX_TO_ATLAS   - optional, by default is False. tell packer if upload the vagrant box generated to ATLAS. NOTE: ATLAS user/token and target ATLAS repo name should be specificed.
+# * ATLAS_USERNAME - optional, required only when UPLOAD_BOX_TO_ATLAS is true.
+# * ATLAS_NAME     - optional, required only when UPLOAD_BOX_TO_ATLAS is true.
+# * ATLAS_TOKEN    - optional, required only when UPLOAD_BOX_TO_ATLAS is true.
+# * ATLAS_VERSION  - optional, by default is "".when UPLOAD_BOX_TO_ATLAS is true, the box will be uploaded to ATLAS as ATLAS_VERSION( format only accepts like 1.2.3).
 ###################################################
 
 
@@ -13,18 +19,71 @@
 # early exit on command failure
 set -e
 
-#Ubuntu Version, can become an ENV VAR in the future
+echo '[Info] Please use ENV VAR to pass customized parameter to this script. Please refer to the usage on the top of script file.'
+
+############################  Parameter Process ################ start #############
+
+#Ubuntu Version
 if  [ ! -n "${OS_VER}" ];  then
     OS_VER=ubuntu-14.04
 fi
-echo "Packer Build based on $OS_VER"
+echo "[Info] Packer Build based on $OS_VER"
 
-# Build Vagrant or VMware OVA
+# Build Vagrant or VMware OVA ?
 if  [ ! -n "${BUILD_TYPE}" ];  then
-    BUILD_TYPE=vmware  # option is vmware or vitrualbox , case senstive
+    BUILD_TYPE=virtualbox  # option is vmware or vitrualbox , case senstive
+fi
+
+echo "[Info] Packer Build : ${BUILD_TYPE}"
+
+
+IS_UPLOAD_ATLAS=false
+if [[ "${UPLOAD_BOX_TO_ATLAS}" == "true" ]] ||  [[ "${UPLOAD_BOX_TO_ATLAS}" == "TRUE" ]];
+then
+    IS_UPLOAD_ATLAS=true
+fi
+if [ $BUILD_TYPE != "virtualbox" ] && [ $IS_UPLOAD_ATLAS == true ]; then
+    echo "[Error]: Bad Env Var: only when for Vagrant Box build. ( BUILD_TYPE=virtualbox), the $UPLOAD_BOX_TO_ATLAS can be set to true . Abort !"
+    exit 1
+fi
+if [ $IS_UPLOAD_ATLAS == true ]; then
+   if [ ! -n "${ATLAS_USERNAME}" ] || [ ! -n "${ATLAS_NAME}" ] || [ ! -n "${ATLAS_TOKEN}" ];  then
+       echo "[Error]: Bad Env Var: When ENV VAR \$UPLOAD_BOX_TO_ATLAS is true, the ATLAS_USERNAME/ATLAS_NAME/ATLAS_TOKEN should be given.  Abort !"
+       exit 2
+   fi
+   if [ ! -n "${ATLAS_VERSION}" ];  then
+       ATLAS_VERSION=""
+   else
+       if [[ $ATLAS_VERSION != +([0-9]).+([0-9]).+([0-9]) ]] ; then
+           echo "[Error]: ATLAS_VERSION(${ATLAS_VERSION}) should be X.Y.Z (X.Y.Z is digit), that's only format accepted by ATLAS."
+          exit 2
+      fi
+   fi
 fi
 
 
+# By default. use ansible playbook : rackhd_local.yml
+# can become an ENV VAR in the future
+if  [ ! -n "${RACKHD_INSTALL_ANSIBLE}" ];  then
+    RACKHD_INSTALL_ANSIBLE=rackhd_local
+fi
+echo "[Info] Install RackHD with ansible :  ${RACKHD_INSTALL_ANSIBLE}.yml "
+
+
+
+if [  -n "${RACKHD_VERSION}" ];  then
+   if [ $RACKHD_INSTALL_ANSIBLE != "rackhd_local" ]; then
+       echo "[Info] Build VM based on RackHD Debian Package ${RACKHD_VERSION} "
+  else
+       echo "[Warning] Skip the ENV VAR: RACKHD_VERSION=$RACKHD_VERSION, this variable is useless for rackhd_local.yml (build from src code)".
+   fi
+else
+   if [ $RACKHD_INSTALL_ANSIBLE != "rackhd_local" ]; then
+       echo "[Info] Install RackHD Package without specific version."
+   fi
+fi
+
+############################  Parameter Process ################ end #############
 
 # Enable Verbose Packer Logging
 # see https://www.packer.io/docs/other/environmental-variables.html for details
@@ -32,13 +91,6 @@ export PACKER_LOG=1
 export PACKER_LOG_PATH=./packer-debug.log
 export PACKER_NO_COLOR=1  # for Jenkins usage. if manual run, suggest to turn color on (set to 0)
 
-
-# By default. use ansible playbook : rackhd_package.yml
-# can become an ENV VAR in the future
-if  [ ! -n "${RACKHD_INSTALL_ANSIBLE}" ];  then
-    RACKHD_INSTALL_ANSIBLE=rackhd_package
-fi
-echo "Install RackHD with ansible ${RACKHD_INSTALL_ANSIBLE}.yml"
 
 
 
@@ -48,9 +100,22 @@ VMDIR=output-${BUILD_TYPE}-iso
 VM_NAME=rackhd-${OS_VER}
 
 
+CFG_FILE=template.cfg
 # parameter file pass to packer
-echo { \"playbook\": \"${RACKHD_INSTALL_ANSIBLE}\",   > template.cfg
-echo  \"vm_name\": \"${VM_NAME}\" } >> template.cfg
+echo {                                                > $CFG_FILE
+echo  \"playbook\": \"${RACKHD_INSTALL_ANSIBLE}\",   >> $CFG_FILE
+echo  \"vm_name\": \"${VM_NAME}\"                    >> $CFG_FILE
+
+if [[ $IS_UPLOAD_ATLAS == true ]]
+then
+    echo ,                                           >> $CFG_FILE
+    echo \"atlas_username\": \"${ATLAS_USERNAME}\" , >> $CFG_FILE
+    echo \"atlas_name\": \"${ATLAS_NAME}\" ,         >> $CFG_FILE
+    echo \"atlas_token\": \"${ATLAS_TOKEN}\" ,       >> $CFG_FILE
+    echo \"atlas_version\": \"${ATLAS_VERSION}\"     >> $CFG_FILE
+fi
+echo }                                               >> $CFG_FILE
+# parameter file --- done
 
 
 PACKER=packer
@@ -67,8 +132,8 @@ else
 fi
 
 
+# Check Free Disk Space,  VMWare Workstation may stuck if disk space too small
 if [ "$BUILD_TYPE"  == "vmware" ];  then
-    # Check Free Disk Space,  VMWare Workstation may stuck if disk space too small
     fd_in_kb=$(df  .  | awk '/^\/dev/ {print $4}')
     fd_thres=$(expr 1024 '*' 1024 '*' 8)  # set to 8G as threshold.
     if [ $fd_in_kb -lt  $fd_thres ]
@@ -78,11 +143,25 @@ if [ "$BUILD_TYPE"  == "vmware" ];  then
     fi
 fi
 
-#build RackHD OVA
-$PACKER build --force --only=${BUILD_TYPE}-iso --var-file=template.cfg template-${OS_VER}.json | $TS | tee packer-install.log
+# pre-process the packer template file
+PACKER_TEMP=$(cat template-${OS_VER}.json)
+if [[ $IS_UPLOAD_ATLAS == false ]]
+then
+    if [ ! -n "$(which jq)" ] ; then
+        echo "[Error] jq is not installed . please install it, e.x. sudo apt-get install jq... Aborting. "
+        exit 5
+    fi
+    # Delete the post-processors blocks in the template.json, before sending to 'packer build'
+#    PACKER_TEMP=$( jq 'del(."post-processors")'  template-${OS_VER}.json)
+     PACKER_TEMP=$( jq 'del(.["post-processors", "push"])' template-${OS_VER}.json)
+fi
+
+
+# execute 'packer build'
+echo ${PACKER_TEMP} | $PACKER build --force --only=${BUILD_TYPE}-iso --var-file=$CFG_FILE  - | $TS | tee packer-install.log 
 
 if [ $? != 0 ]; then
-    echo "Packer Build failed.. exit"
+    echo "[Error] Packer Build failed.. exit"
     exit 3
 fi
 
@@ -96,9 +175,9 @@ fi
 if [ -f "$CI_SIGNING_KEY" ]
 then
     SIGN_ARGS="--privateKey=$CI_SIGNING_KEY"
-    echo "Signing the OVA with the CI key"
+    echo "[Info]Signing the OVA with the CI key"
 else
-    echo "No signing to be performed.. skip."
+    echo "[Info]No signing to be performed.. skip."
 fi
 
 # Conver the VM Disk and VMX folder into an OVA
@@ -108,18 +187,18 @@ OVA="${BASENAME}.ova"
 ovftool $SIGN_ARGS -o ${VMDIR}/${VM_NAME}.vmx $OVA
 
 if [ $? != 0 ]; then
-    echo "ovftool exec failed.. exit"
+    echo "[Error] ovftool exec failed.. exit"
     exit 4
 fi
 
 # Do Virus Scan
 if [ -x /usr/bin/clamscan ]
 then
-    echo "Doing ClamScan"
+    echo "[Info] Doing ClamScan"
     rm -rf "$OVA.avscan"
     /usr/bin/clamscan --log="$OVA.avscan" --max-filesize=4000M --max-scansize=4000M -r ${VMDIR} --allmatch
 else
-    echo "skip clamscan..."
+    echo "[Info] skip clamscan..."
 fi
 
 
